# Generated by Django 5.1.6 on 2025-03-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_notaentrada_detallenotaentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrada',
            name='articulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
