# Generated by Django 5.1.6 on 2025-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_detallenotaentrada_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotaentrada',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
