# Generated by Django 5.1.6 on 2025-03-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_salida_detallesalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaentrada',
            name='proveedor',
            field=models.CharField(max_length=255),
        ),
    ]
