# Generated by Django 5.1.6 on 2025-03-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_notaentrada_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='proveedor',
            field=models.CharField(max_length=255),
        ),
    ]
