# Generated by Django 5.1.6 on 2025-03-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_alter_salida_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.proveedor'),
        ),
    ]
